spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

server:
  port: 8080

jwt:
  access-token-secret: ${JWT_ACCESS_TOKEN_SECRET}
  refresh-token-secret: ${JWT_REFRESH_TOKEN_SECRET}
  access-token-expiration-ms: 1800000
  refresh-token-expiration-ms: 1209600000
