spring:
  application:
    name: auth-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

jwt:
  access-token-secret: ${JWT_ACCESS_TOKEN_SECRET:}
  refresh-token-secret: ${JWT_REFRESH_TOKEN_SECRET:}
  access-token-expiration-ms: 1800000
  refresh-token-expiration-ms: 1209600000
