apiVersion: v1
kind: Secret
metadata:
  name: atlas-app-secret
  namespace: atlas
type: Opaque
stringData:
  AUTH_DB_PASSWORD: "EXAMPLE_CHANGE_ME"
  SUPPLY_DB_PASSWORD: "EXAMPLE_CHANGE_ME"
  CONTROL_DB_PASSWORD: "EXAMPLE_CHANGE_ME"
  FILE_DB_PASSWORD: "EXAMPLE_CHANGE_ME"
  AWS_ACCESS_KEY_ID: "EXAMPLE_CHANGE_ME"
  AWS_SECRET_ACCESS_KEY: "EXAMPLE_CHANGE_ME"
