apiVersion: v1
kind: Secret
metadata:
  name: atlas-jwt-secret
  namespace: atlas
type: Opaque
stringData:
  JWT_ACCESS_TOKEN_SECRET: "EXAMPLE_CHANGE_ME_ACCESS_SECRET"
  JWT_REFRESH_TOKEN_SECRET: "EXAMPLE_CHANGE_ME_REFRESH_SECRET"
