spring:
  config:
    activate:
      on-profile: prod
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8080
          predicates:
            - Path=/api/auth/**
        - id: supply-service
          uri: http://supply-service:8080
          predicates:
            - Path=/api/supply/**
        - id: control-service-ws
          uri: ws://control-service:8080
          predicates:
            - Path=/ws-control/**
        - id: control-service-ws-root
          uri: ws://control-service:8080
          predicates:
            - Path=/ws-control
        - id: control-service-ws-api
          uri: ws://control-service:8080
          predicates:
            - Path=/api/control/ws-control/**
          filters:
            - StripPrefix=2
        - id: control-service-ws-chat
          uri: ws://control-service:8080
          predicates:
            - Path=/ws-chat/**
        - id: control-service-ws-chat-root
          uri: ws://control-service:8080
          predicates:
            - Path=/ws-chat
        - id: control-service-ws-chat-api
          uri: ws://control-service:8080
          predicates:
            - Path=/api/control/ws-chat/**
          filters:
            - StripPrefix=2
        - id: control-service
          uri: http://control-service:8080
          predicates:
            - Path=/api/control/**
        - id: file-service
          uri: http://file-service:8080
          predicates:
            - Path=/api/files/**

server:
  port: 8080

jwt:
  access-token-secret: ${JWT_ACCESS_TOKEN_SECRET}

auth-service:
  url: http://auth-service:8080

supply-service:
  url: http://supply-service:8080
