spring:
  config:
    activate:
      on-profile: prod
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8080
          predicates:
            - Path=/api/auth/**
        - id: supply-service
          uri: http://supply-service:8080
          predicates:
            - Path=/api/supply/**
        - id: control-service
          uri: http://control-service:8080
          predicates:
            - Path=/api/control/**
        - id: file-service
          uri: http://file-service:8080
          predicates:
            - Path=/api/files/**

server:
  port: 8080

jwt:
  access-token-secret: ${JWT_ACCESS_TOKEN_SECRET}

auth-service:
  url: http://auth-service:8080

supply-service:
  url: http://supply-service:8080
