spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

  elasticsearch:
    uris: ${ELASTICSEARCH_URIS}
