spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
supply-service:
  url: http://supply-service:8080/
server:
  port: 8080
