spring:
  profiles:
    active: local
  application:
    name: control-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
