apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-service
  namespace: atlas
spec:
  replicas: 3
  selector:
    matchLabels:
      app: control-service
  template:
    metadata:
      labels:
        app: control-service
    spec:
      containers:
        - name: control-service
          image: <AWS_ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/atlas-control:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: atlas-secrets
                  key: POSTGRES_HOST
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://$(DB_HOST):5432/control_db
            - name: SPRING_DATASOURCE_USERNAME
              value: atlas
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: atlas-secrets
                  key: POSTGRES_PASSWORD
            - name: SPRING_DATA_REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: atlas-secrets
                  key: REDIS_HOST
            - name: SPRING_DATA_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: atlas-secrets
                  key: REDIS_PASSWORD
            - name: SPRING_ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: atlas-secrets
                  key: ELASTICSEARCH_USERNAME
            - name: SPRING_ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: atlas-secrets
                  key: ELASTICSEARCH_PASSWORD
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: ATLAS_REDIS_NOTIFICATION_DATABASE
              value: "2"
            - name: ATLAS_REDIS_CHAT_DATABASE
              value: "3"
            - name: SPRING_ELASTICSEARCH_URIS
              value: http://elasticsearch-service:9200
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka-service:9092
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
