spring:
  profiles:
    active: local
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    path: /api/files/v3/api-docs
  swagger-ui:
    path: /api/files/swagger-ui.html
    url: /api/files/v3/api-docs
    disable-swagger-default-url: true
    operations-sorter: method
    tags-sorter: alpha
