spring:
  profiles:
    active: local
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
