spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mariadb://localhost:3306/supply_db
    username: atlas
    password: atlas
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8082
