spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

server:
  port: 8080

atlas:
  auth-service:
    base-url: ${ATLAS_AUTH_SERVICE_BASE_URL}
  geocoding:
    kakao:
      base-url: ${ATLAS_KAKAO_GEOCODING_BASE_URL:https://dapi.kakao.com}
      rest-api-key: ${KAKAO_REST_API_KEY}
