spring:
  profiles:
    active: prod
    group:
      local:
        - batch
  application:
    name: supply-service
  jackson:
    deserialization:
      accept-float-as-int: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    path: /api/supply/v3/api-docs
  swagger-ui:
    path: /api/supply/swagger-ui.html
    url: /api/supply/v3/api-docs
    disable-swagger-default-url: true
    operations-sorter: method
    tags-sorter: alpha
