CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS supply_db;
CREATE DATABASE IF NOT EXISTS file_db;

GRANT ALL PRIVILEGES ON auth_db.* TO 'atlas'@'%';
GRANT ALL PRIVILEGES ON supply_db.* TO 'atlas'@'%';
GRANT ALL PRIVILEGES ON file_db.* TO 'atlas'@'%';

FLUSH PRIVILEGES;
