CREATE DATABASE IF NOT EXISTS auth_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS supply_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS file_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

GRANT ALL PRIVILEGES ON auth_db.* TO 'atlas'@'%';
GRANT ALL PRIVILEGES ON supply_db.* TO 'atlas'@'%';
GRANT ALL PRIVILEGES ON file_db.* TO 'atlas'@'%';

FLUSH PRIVILEGES;
